### ISSUE TITLE
Update "Powered by Geodesic Solutions, LLC" branding

### ISSUE THREAD

**Issue by vicos59** [geodesicsolutions-community/geocore-community#113]
It also links to geodesicsolutions.com.

I used "Site Text Search" and did not find it.

Can be disabled in admin:

http://localhost:8080/admin/index.php?page=main_general_settings&mc=site_setup

**Comment by vicos59** [comment]
@jonyo I don't know if you automagically get notified of my new pull requests, so I am tagging you.

**Comment by jonyo** [comment]
>  I don't know if you automagically get notified of my new pull requests, so I am tagging you.

Yes I do now!  I have notifications set up for any activity in this repo, for anything including discussions, issues, pr's, etc.

**Comment by jonyo** [comment]
Closing this, the PR #121 fixes it.

@vicos59 I think it did not auto close because you had `issue` in between like `fixes issue #` instead of just `fixes #`.

For more details on how the auto linking / closing works, see [these docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
