### ISSUE TITLE
Manage Addons: No User Feedback that Action was Completed

### ISSUE THREAD

**Issue by vicos59** [geodesicsolutions-community/geocore-community#55]
![bug-03](https://user-images.githubusercontent.com/6634041/153033341-c83a5042-9961-4e0b-b630-fcb019cfc7cd.JPG)

There is no feedback that requested action has been completed. For example, if you click 'Enable' or 'Disable' next to an AddOn, there is no change on the page. You do not see that your requested action has been completed unless you refresh the page.

I assume this is a Javascript issue. Tested on Brave and Firefox.

Confirmed that it does provide confirmation of user actions on v7.5.1

Same problem on **Manage Regions** pages. May be others that use the same code.

**Comment by jonyo** [comment]
A fellow brave user! 👍   

Also, side note, this is the first issue opened in the repo by someone besides me!  🥳

**Comment by WOs8lfTkz3E5g7I4Lm** [comment]
I wasn't sure if you wanted anyone else opening issues, so I took a shot :)

Appreciate the feedback.

**Comment by jonyo** [comment]
Yes, issues are for anyone to open!  😄

**Comment by WOs8lfTkz3E5g7I4Lm** [comment]
This also impacts the Manage Regions pages. I assume it is the same code in play. May be others as well.

**Comment by jonyo** [comment]
So... I tried to reproduce it just now and could not.  But I did notice Storefront was slow to show the modal saying it was done.

Also I noticed, the "addon enabled" modal does not use an overlay.

So then I tried something, I enabled one that is slow for me (storefront) then I scrolled away - and sure enough, it "appeared" nothing happened!  But really it just happened "off screen" and I did not see it and there was no overlay to give a clue anything happened off screen.  But then since I was watching for it, I noticed the page did reload.

Can you confirm if something like that is happening for you @WOs8lfTkz3E5g7I4Lm ?  Enable an addon, and don't scroll anywhere.  If you can reproduce and it isn't just "off screen" like I saw for me...  Try opening up the JS console and screenshot any errors it shows.  And/or screen video if you are able to do one.

**Comment by WOs8lfTkz3E5g7I4Lm** [comment]
All remarks based on Brave 1.35.101; all shields disabled for this site.

1) In Manage Regions, click on the Red '!' under 'Enabled?'

Nothing happens. Scrolled away and came back and no change. Refresh the page and the change shows (Green Check).

2) Tried 'Manage Addons' and no change. Nothing I did resulted in the visual changes showing until I manually refreshed the page.

Console: Click on Enable/Disable toggle

jquery.min.js?_=fa402:4          POST http://[snip].com/admin/AJAX.php?controller=AddonManage&action=_action&addon=account_balance&task=disable 500 (Internal Server Error)

In Network:

![bug-network](https://user-images.githubusercontent.com/6634041/153464132-c770dbaf-2b88-40f3-a7fc-82f655bcd5dc.JPG)

If I manually load the referenced AJAX.php page, I get a text string back: 'Not authorized'

**Comment by WOs8lfTkz3E5g7I4Lm** [comment]
Well, it looks like I need to try and get PHP 7.4 before I can do any real testing. I am not familiar with composer, but it is enforcing 7.4 when some scripts are run from cli, so, until then. Apologies if most issues reported today are bogus.

**Comment by jonyo** [comment]
> I was running PHP 7.2 and composer was causing a server 500 error when trying to load AJAX.php because it wanted 7.4+.

That is odd...  If it were somehow composer causing an error, it would have to be in the autoloader (which loads the vendor libraries).  And the autoloader is used on every page load, not just AJAX.php loads.  So if it were that, it would happen on any page at all.  I think there is more to this story, it might be worth looking into deeper.

Do you have the actual errors in a log or something?  500 just means something is wrong it doesn't tell you the error.  And I'm curious what lead you to think it had something to do with composer?

One thought I had, just speculating, but it could be a 3rd party addon (or an old version of a geo addon since you are upgrading, if we have removed the addon since then it would still be using old files).  We now use adodb (for database) in a different folder, I wonder if might be trying to load the old location?  Then it might cause an error trying to load 2 versions of ADODB.  I mean, just guessing, if you are able to get actual errors we could tell more.

**Comment by WOs8lfTkz3E5g7I4Lm** [comment]
`Do you have the actual errors in a log or something? 500 just means something is wrong it doesn't tell you the error. And I'm curious what lead you to think it had something to do with composer?`

I was trying to track down what was causing the 500 errors and couldn't find any log info or runtime errors. So, I tried running both scripts CLI. That's when I got the Composer warning about 7.4. The 500 error was likely caused because composer was not outputting any http headers.

`since you are upgrading`

So far I have only been working with a fresh install of 20.0.0. Now that the major errors have been resolved, I am ready to try a test upgrade of a 7.5.1 site.

**Comment by jonyo** [comment]
> So, I tried running both scripts CLI

How did you do that?  Like if I wanted to do the same thing, what do I do, what commands etc?  And specifically what was the command that showed a warning about composer?

Like I mentioned, if something about composer itself did not work on PHP 7.2 then the entire site would not work.  So it is specific to the ajax calls.

> So far I have only been working with a fresh install of 20.0.0

Ah ok, that rules out some things like something trying to load libraries from the old location.  Unless I missed a spot in the main code base, but if I did, it "should" affect me too.

> I didn't see any composer config files, so I don't know where it is getting the min requirements from.

The composer config is in `composer.json` but that is not part of the zip file, that is in the source code.

**Comment by WOs8lfTkz3E5g7I4Lm** [comment]
P.S. I can grant you access to my test site with shell if you like.

**Comment by jonyo** [comment]
>  I can't remember for sure. Anyway it is there now if you run B3 on 7.2 on my machine.

I looked into it more, the autoloader does end up giving a 500 error if it detects the PHP version is too low.  Like it is actually coded to give the 500 header.  Mind you, it does not stop things from working, it is meant to just warn you about it.  But in this case I think the 500 makes the JS not work, it thinks the call failed (when it did not), so you get problems.

When I lower the required PHP version in the update / setup scripts, at that point I'll lower it in composer as well and it should solve it.

If you want to mess with it, I found where it does it, look buried in `vendor/composer/platform_check.php` and find `PHP_VERSION_ID >= 70400` and change to `PHP_VERSION_ID >= 70200` and that should do the trick.
